#!/bin/sh

userx11dir="${XDG_CONFIG_HOME:-$HOME/.config}/X11"

userresources="$userx11dir/Xresources"
usermodmap="$userx11dir/Xmodmap"
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

[[ -f "$userx11dir/xprofile" ]] && . "$userx11dir/xprofile"

# start window manager

session=${1:-bspwm}

case $session in
    i3|i3wn        ) exec i3;;
    bspwm          ) exec bspwm;;
    # no known session, try to run it as a command
    *              ) exec $1;;
esac