#!/bin/sh

xrandr --dpi 96

setxkbmap -option ctrl:nocaps &

xset r rate 300 50 &

autostart="mpd dunst clipmenu pipewire"
for program in $autostart; do
	pidof -s "$program" || "program" &
done >/dev/null 2>&1
