#!/bin/sh

# These are the custom commands and programs to run for all window managers.

xrandr --dpi 96

xset r rate 300 50 &

xsetroot -cursor_name left_ptr &

xset s 300 5 &
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

setxkbmap us,se -option ctrl:nocaps &

autostart="mpd dunst clipmenu pipewire"
for program in $autostart; do
	pidof -s "$program" || "program" &
done >/dev/null 2>&1

[[ -f "$HOME/.dotfiles/refresh-system-info.sh" ]] && bash $HOME/.dotfiles/refresh-system-info.sh &
