attribute = "gray9"
keyword = "gray9"
"keyword.directive" = "gray9" # -- preprocessor comments (#if in C)
namespace = "gray9"
punctuation = "gray9"
"punctuation.delimiter" = "gray9"
operator = "gray9"
special = "gray9"
"variable.other.member" = "gray9"
variable = "gray9"
# variable = "gray9" # TODO: metavariables only
# "variable.parameter" = { fg = "gray9", modifiers = ["gray9"] }
"variable.parameter" = { fg = "gray9" }
"variable.builtin" = "gray9"
type = "gray9"
"type.builtin" = "gray9" # TODO: distinguish?
constructor = "gray9"
function = "gray9"
"function.macro" = "gray9"
"function.builtin" = "gray9"
tag = "gray9"
comment = "gray9"
constant = "gray9"
"constant.builtin" = "gray9"
string = "gray9"
"constant.numeric" = "gray9"
"constant.character.escape" = "gray9"
# used for lifetimes
label = "gray9"

"diff.plus" = "green"
"diff.minus" = "pink"
"diff.delta" = "slate"

"ui.background" = { bg = "slate" }
"ui.background.separator" = { fg = "gray9" }
"ui.linenr" = { fg = "gray9" }
"ui.linenr.selected" = { fg = "gray9" }
"ui.statusline" = { fg = "gray9", bg = "gray1" }
"ui.statusline.inactive" = { fg = "gray9", bg = "gray1" }
"ui.popup" = { fg = "gray9", bg = "gray1" }
"ui.window" = { fg = "gray1" }
"ui.help" = { fg = "gray9", bg = "gray1" }

"ui.text" = { fg = "gray9" }
"ui.text.focus" = { fg = "gray9" }
"ui.virtual" = { fg = "gray9" }

"ui.virtual.indent-guide" = { fg = "gray9" }

"ui.selection" = { bg = "teal" }
"ui.selection.primary" = { bg = "teal" }

"ui.menu" = { fg = "gray9", bg = "gray1" }
"ui.menu.selected" = { fg = "gray1", bg = "gray9" }

hint = "deepCerulian" # Experiment with this...
info = "gray3"
warning = "yellow"
error = "pink"

"diagnostic.hint" = { underline = { color = "deepCerulian", style = "curl" } } # Experiment with this...
"diagnostic.info" = { underline = { color = "gray3", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "pink", style = "curl" } }

[palette]
gray1 = "#202224"
gray2 = "#2d2d2d"
gray3 = "#555759"
gray4 = "#6e7072"
gray5 = "#848688"
gray6 = "#aaacae"
gray7 = "#c6c8ca"
gray8 = "#dcdee0"
gray9 = "#f0f1f2"
gray10 = "#f8f8f8"
turqLight = "#5dc9e2"
turqMed = "#50b7e0"
turqDark = "#007d9c"
abbey = "#3f4042"
blue = "#bfeaf4"
blueLight = "#f2fafd"
black1 = "#000000"
black2 = "#111111"
deepCerulian = "#007f9f"
green = "#3a6e11"
greenLight = "#5fda64"
pink = "#c85e7a"
pinkLight = "#fdecf1"
purple = "#542c7d"
shark = "#2b2d2f"
slate = "#253443"
tundora = "#414141"
white = "#ffffff"
yellow = "#fddd00"
yellowLight = "#fff8cc"
testimonial = "#007f9f"
teal = "#006666"