# theme = "rose_pine_dawn" # Light theme
theme = "rose_pine" # Dark theme

[editor]
line-number = "relative"
mouse = false
cursorline = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "file-name", "spinner"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

# [editor.indent-guides]
# render = true

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
'{' = ["goto_prev_paragraph", "collapse_selection", "move_line_up"]
'}' = ["goto_next_paragraph", "collapse_selection"]
'C-u' = ["page_up", "align_view_center"]
'C-d' = ["page_down", "align_view_center"]
'A-w' = ":write"
'A-y' = ['extend_to_line_bounds', 'trim_selections', 'yank'] # Copy line with one leading whitesapce and all trailing whitespace removed.
# Do gll<insert mode + ' '><normal_mode>Y to paste next to current line

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
'A-w' = ["normal_mode", ":write"]
