theme = "jacme" 

[editor]
# line-number = "relative"
mouse = false
cursorline = true
bufferline = "multiple"
color-modes = true
true-color = true
undercurl = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["file-modification-indicator", "file-name"]
center = ["version-control"]
right = ["position", "separator", "spacer", "position-percentage", "spacer", "separator", "total-line-numbers", "spacer", "spacer"]
separator = "│"

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

[keys.normal]
X = "extend_line_above"
i = [":toggle lsp.display-inlay-hints", "insert_mode"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal.space]
q = ":quit"
w = ":write"

[keys.insert]
esc = [":toggle lsp.display-inlay-hints", "normal_mode"]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"
