#! /bin/sh

pgrep -x picom > /dev/null || picom --config "$HOME/.config/picom/picom.conf" --experimental-backends --vsync &

pgrep -x sxhkd > /dev/null || sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
