#! /bin/sh
$HOME/.config/bspwm/autostart.sh

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '1' '2' '3' '4' '5' '6'
		let name++
	done
}

workspaces

# Global Settings
bspc config gapless_monocle false
bspc config borderless_monocle false
bspc config single_monocle true
bspc config split_ratio 0.5
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier control
bspc config pointer_action1 resize_corner
bspc config pointer_action2 move
bspc config pointer_action3 none
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# Desktop Settings
bspc config window_gap          12

# Node Settings
bspc config border_width         2

# Rules
bspc rule -r "*" # Remove any previously added rules

# Do xprop check for app names.
bspc rule -a Alacritty desktop='^1'
bspc rule -a org.wezfurlong.wezterm desktop='^1'
bspc rule -a Code desktop='^2'
bspc rule -a firefox desktop='^3'
bspc rule -a Slack desktop='^5'
bspc rule -a Bitwarden desktop='^5'
