#! /bin/sh
$HOME/.config/bspwm/autostart.sh

bspc monitor -d I II III IV V VI VII VIII IX X

# Global Settings
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config single_monocle true
bspc config split_ratio 0.52
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier control
bspc config pointer_action1 resize_corner
bspc config pointer_action2 move
bspc config pointer_action3 none
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer false
bspc config click_to_focus true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# Desktop Settings
bspc config window_gap          12

# Node Settings
bspc config border_width         2

# Rules
bspc rule -r "*" # Remove any previously added rules
